#!/bin/bash

source ../settings/scripts/_common.sh
source ../settings/scripts/experimental_helper.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

if systemctl is-active "$app".service --quiet; then
    ynh_print_warn "It's hightly recommended to make your backup when the service is stopped. Please stop $app service with this command before to run the backup 'systemctl stop $app.service'"
fi

ynh_print_info "Declaring files to be backed up..."

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

# BACKUP THE PHP-FPM CONFIGURATION
ynh_backup "/etc/php/$php_version/fpm/pool.d/$app.conf"

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf.inc"

# Backup only server name config if it exist
if [ -e "/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf" ]; then
    ynh_backup "/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf"
fi

#=================================================
# BACKUP THE POSTGRESQL DATABASE
#=================================================

ynh_psql_dump_db > ${YNH_CWD}/dump.sql

#=================================================
# BACKUP FAIL2BAN CONFIGURATION
#=================================================

ynh_backup "/etc/fail2ban/jail.d/$app.conf"
ynh_backup "/etc/fail2ban/filter.d/$app.conf"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP SYNAPSE CONFIG
#=================================================

ynh_backup "/etc/matrix-$app"

#=================================================
# BACKUP SYSTEMD
#=================================================

ynh_backup "/etc/systemd/system/$app.service"
ynh_backup "/etc/systemd/system/$app-coturn.service"
ynh_backup /etc/systemd/system/"$app"-livekit.service
ynh_backup /etc/systemd/system/"$app"-lk-jwt.service

#=================================================
# BACKUP SYNAPSE DATA
#=================================================

ynh_backup "$data_dir"

#=================================================
# BACKUP SYNAPSE LOG
#=================================================

ynh_backup "/var/log/matrix-$app"

#=================================================
# BACKUP HOOKS
#=================================================

# Copy hook
ynh_backup "/etc/yunohost/hooks.d/post_cert_update/50-$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
