#!/bin/bash

source ./experimental_helper.sh
source ./_common.sh
source /usr/share/yunohost/helpers

ynh_app_config_validate() {
    # Depending of the status of the $enable_regirtration we should default value of the hidden fields
    if $enable_registration; then
        # Must enable password authentication when free registration is enabled as any user must be able to authenticate
        password_enabled=true
    else
        registrations_require_3pid=email
        allowed_local_3pids_email=''
        allowed_local_3pids_msisdn=''
        disable_msisdn_registration=true
    fi
    _ynh_app_config_validate
}

ynh_app_config_apply() {
    _ynh_app_config_apply
    configure_nginx
    ynh_config_add --jinja --template="homeserver.yaml" --destination="/etc/matrix-$app/homeserver.yaml"
    ynh_config_add --template="log.yaml" --destination="/etc/matrix-$app/log.yaml"
    set_permissions
}

#=================================================
# SELECT THE ACTION FOLLOWING THE GIVEN ARGUMENT
#=================================================
ynh_app_config_run "$1"
