#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source experimental_helper.sh
source /usr/share/yunohost/helpers

#=================================================
# SET CONSTANTS
#=================================================

synapse_user="matrix-$app"
upstream_version=$(ynh_app_upstream_version)
final_www_path="/var/www/$app"

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status matrix-$app >/dev/null
then
    ynh_script_progression --message="Removing matrix-$app service integration..." --weight=1
    yunohost service remove matrix-$app
fi

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status coturn-$app >/dev/null
then
    ynh_script_progression --message="Removing coturn-$app service integration..." --weight=1
    yunohost service remove coturn-$app
fi

ynh_remove_systemd_config --service=matrix-$app
ynh_remove_systemd_config --service=coturn-$app

# Remove the dedicated NGINX config
ynh_remove_nginx_config

# Remove the dedicated PHP-FPM config
ynh_remove_fpm_config

# Remove the app-specific logrotate config
ynh_remove_logrotate

# Remove the dedicated fail2ban config
ynh_remove_fail2ban_config

# Remove other various files specific to the app...

ynh_secure_remove --file=$final_www_path
ynh_secure_remove --file=/var/log/matrix-$app
ynh_secure_remove --file=/etc/matrix-$app
ynh_secure_remove --file=/etc/default/matrix-$app
ynh_secure_remove --file=/etc/default/coturn-$app
ynh_secure_remove --file=/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf

# Delete a system user
ynh_system_user_delete --username=$synapse_user

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
